services:
  postgres:
    container_name: threads-db
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: threadsdb

volumes:
  postgres-data:
